# Generated by Django 3.1.1 on 2020-09-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20200906_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account',
            new_name='name',
        ),
    ]
