# Generated by Django 3.1 on 2020-09-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_auto_20200912_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='owner',
        ),
    ]
